#pragma config(Sensor, S1,     SDD,            sensorEV3_Ultrasonic)		//Sensor distancia, direita
#pragma config(Sensor, S2,     SRD,            sensorEV3_Color)					//Sensor refletancia, direita
#pragma config(Sensor, S3,     SRE,            sensorEV3_Color)					//Sensor refletancia, esquerda
#pragma config(Sensor, S4,     SDE,            sensorEV3_Ultrasonic)		//Sensor distancia, esquerda
#pragma config(Motor,  motorA,          MF,            tmotorEV3_Large, PIDControl, encoder) //MF-frente
#pragma config(Motor,  motorB,          ME,            tmotorEV3_Large, PIDControl, encoder) //ME-Esquerda
#pragma config(Motor,  motorC,          MD,            tmotorEV3_Large, PIDControl, encoder) //MD-Direita
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int se=0, sd=0, srea=0, srda=0, rodar=1, contador=0;	//srea,a=atual

task main()
{
	while(contador<5){
		se=se+SensorValue[SDE];
		sd=sd+SensorValue[SDD];
		delay(970);
		contador=contador+1;
	}
	se=se*0.2;
	sd=sd*0.2;

	if(sd<40)
		rodar=-1;

	motor[MD] = 100;
	motor[ME] = 100;
	motor[MF] = -100;
	delay(450);

	while(1){
		srea=SensorValue[SRE];
		srda=SensorValue[SRD];
		if(srea<5&&srda<5){
			se=SensorValue[SDE];
			sd=SensorValue[SDD];
			if(sd<40&&se<40){
				motor[MD] = 100;
				motor[ME] = 100;
			}
			if(sd<40&&se>40){
				motor[MD] = 50;
				motor[ME] = 100;
				rodar=1;
			}
			if(sd>40&&se<40){
				motor[MD] = 100;
				motor[ME] = 50;
				rodar=-1;
			}
			if(sd>40&&se>40){
				motor[MD]=-60*rodar;
				motor[ME]=60*rodar;
			}
		}
		if(srea>5&&srda<5){
			motor[MD]=-60;
			motor[ME]=-60;
			delay(350);
			rodar=1;
		}
		if(srea<5&&srda>5){
			motor[MD]=-60;
			motor[ME]=-60;
			delay(350);
			rodar=-1;
		}
		if(srea>5&&srda>5){
			motor[MD]=-100;
			motor[ME]=-100;
			delay(500);
			motor[MD]=80*rodar;
			motor[ME]=-80*rodar;
			delay(150);
		}
	}
}
